### ISSUE TITLE
Transport

### ISSUE THREAD

**Issue by RuanEsterhuizen** [COS214-Project-2024/TheCityKings#6]

**Comment by RuanEsterhuizen** [comment]
I have added the classes and the basic implementation from the class diagram, but I have thought of a basic way to integrate transport in the system:

- Every transport has a cost now and gets added to the city, maybe City has functions like buildRoad(),..
- The modes of transport that transports people (roads, busses) affects citizen satisfaction: When there are buildings that are not connected/ total transport capacity exceeds the city populations, the satisfaction rate drops
- The modes of transport that transport goods (airports, ferries) affects the economy, I think the city should get a general score for the economy and the more of these modes of transport can be one of the things that increases that score

**Comment by tomschulz02** [comment]
I think thats a good idea. That way its still simple but has an impact on the simulation. I think it would be over the top to handle transport for each individual citizen, so if we just keep it like that where its more about availability and capacity than anything else.

We might not need to have to build roads and have methods for those, but rather infer the existence of a road when two adjacent blocks/suburbs have the same transport available

**Comment by RuanEsterhuizen** [comment]
Ok, I will replace roads with some other public transport

I also might add a basic template method for a print function
